---
title: "Fizikokimyasal Özelliklerinden Yola Çıkarak Beyaz Şarap Tercihlerinin Tahmini"
author: 
  - Fırat Kıl [18080094]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[Github Repo](https://github.com/firatkill/arasinav)


## Giriş

   Beyaz şaraplar, şarap dünyasının en zarif ve çeşitli tatlarından bazılarını sunan ferahlatıcı içeceklerdir. Beyaz şarapların üretiminde kullanılan üzümler ve üretim süreci, lezzet, koku ve dokularında önemli bir rol oynar. Ayrıca, beyaz şarapların fizikokimyasal özellikleri, renk, asitlik, alkol oranı ve tat profilleri gibi faktörler de birçok kişinin tercih ettiği belirli bir tarza sahip olmasına neden olur. Bu çalışmada, beyaz şarapların fizikokimyasal özelliklerine ve bu özelliklerin tercih edilen tat profillerine nasıl etki ettiğine dair, 12 değişkenli veri setinden yola çıkılarak, detaylı bir analiz sunulacaktır. Veri setinde bu değişkenlere ait 77 farklı gözlem bulunmaktadır.

Veri setinde aşağıdaki değişkenler bulunmaktadır;

 * **Sabit asidite**
 * **Uçucu asidite:** _Normal basınçta düşük kaynama-buharlaşma sıcaklığına sahip olan, enerji metabolizmasında kullanılan propiyonik, bütirik ve sirke asidi gibi organik asitler._
 * **Sitrik Asit**
 * **Artık şeker:** _Fermantasyon sonucu şarap dibinde kalan doğal üzüm şekeri._
 * **Klorür**
 * **Serbest sülfür dioksit**
 * **Toplam sülfür dioksit**
 * **Yoğunluk**
 * **pH**
 * **Sülfat**
 * **Alkol**
 * **Kalite**
 

## Çalışmanın Amacı

  Bu çalışma ile en eski içeceklerden biri olan şarabın genel karakteristikleri, üretimi, kalitesi ve üzümün hasadından şişelenip ve tüketiciye sunumuna kadar olan süreçlerde kalitesini etkileyen faktörler incelenmiştir. Bu faktörlerden yola çıkarak kullanıcılar tarafından tercih edilen tat profillerine nasıl etki ettiğine dair bir analiz sunulacaktır. 

## Literatür

  Şarap, çok eski tarihlerden beri tüketile gelmekte olan özellikle Yunan ve Roma dönemlerine damgasını vurmuş geleneksel bir içkidir. Özellikle Batı toplumlarında gastronomi ile özdeşleşmiş olan şarap her türlü meyveden üretilmesine rağmen, şarap denilince akla üzüm gelmektedir.[@csen2006csaraplarda] Günümüzde yerli ve yabancı çeşitli markalara ait çok sayıda şarap çeşidi vardır. Bunların bazıları nispeten daha ucuz bazıları da pahalıdır. Fiyat farkı maliyet kadar şarabın kalitesi ile de ilgilidir. Çok sayıda faktör şarapta kaliteyi etkilemektedir. Şaraptaki kalite kriterlerinin bilinmesi ve kalitenin korunması gastronomi alanında önemli bir husustur. [@zeliha2017csarap]
  
Bir zamanlar lüks bir ürün olarak görülen şarap, günümüzde giderek daha geniş bir tüketici yelpazesi tarafından beğenilmektedir. [@ozkan2017bozcaadada] Şarap endüstrisi, büyümesini desteklemek için hem şarap yapımı hem de satış süreçleri için yeni teknolojilere yatırım yapıyor. Şarap sertifikasyonu ve kalite değerlendirmesi bu bağlamda kilit unsurlardır. Sertifikasyon, (insan sağlığını korumak için) şarapların yasa dışı olarak karıştırılmasını önler ve şarap pazarı için kaliteyi garanti eder. Kalite değerlendirmesi genellikle sertifikasyon sürecinin bir parçasıdır ve şarap yapımını iyileştirmek (en etkili faktörleri belirleyerek) ve birinci sınıf markalar gibi şarapları sınıflandırmak (fiyatları belirlemek için yararlıdır) için kullanılabilir.

Şarap sertifikası genellikle fizikokimyasal ve duyusal testlerle değerlendirilir [@chambery2009peptide]. Şarabı karakterize etmek için rutin olarak kullanılan fizikokimyasal laboratuvar testleri, yoğunluk, alkol veya pH değerlerinin belirlenmesini içerirken, duyusal testler esas olarak insan uzmanlara dayanır. Tadın insan duyuları arasında en az anlaşılan [@ubeda2020chemical] olduğu vurgulanmalıdır, bu nedenle şarap sınıflandırması zor bir iştir. Ayrıca, fizikokimyasal ve duyusal analiz arasındaki ilişkiler karmaşıktır ve hala tam olarak anlaşılmamıştır [@samoticha2017effects].

\newpage
# Kaynakça {#references}
<div id="refs"></div>

